[[plugins]]
repo = 'preservim/nerdtree'
hook_add = '''
  source ~/.config/nvim/plugin_config/nerdtree.vim
'''

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
  source ~/.config/nvim/plugin_config/airline.vim
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'
hook_add = '''
  source ~/.config/nvim/plugin_config/ctrlp.vim
'''

[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'
 
[[plugins]]
repo = 'junegunn/fzf.vim'
hook_add = '''
  source ~/.config/nvim/plugin_config/fzf.vim
'''

[[plugins]]
repo = 'mhinz/vim-startify'
hook_add = '''
  source ~/.config/nvim/plugin_config/startify.vim
'''

[[plugins]]
repo = "neoclide/coc.nvim"
merge = 0
rev = "release"
hook_add = '''
  source ~/.config/nvim/plugin_config/coc.vim
'''
